import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowLeft } from 'lucide-react';
import logo from '@/assets/veripeers-logo.png.asset.json';
export const Route = createFileRoute('/privacy')({ head: () => ({ meta: [
  { title: 'Privacy Information — VeriPeers' }, { name: 'description', content: 'How to contact VeriPeers about your early-interest and partnership inquiry details.' },
  { property: 'og:title', content: 'VeriPeers — Privacy Information' }, { property: 'og:description', content: 'Privacy information for VeriPeers pre-launch inquiries and contact details.' },
  { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary' },
] }), component: Privacy });
function Privacy() { return <main className="container privacy-page"><Link to="/"><img src={logo.url} alt="VeriPeers" className="privacy-logo" /></Link><Link to="/" className="back-link"><ArrowLeft size={17} />Back to VeriPeers</Link><p className="eyebrow">YOUR INFORMATION MATTERS</p><h1>Privacy Information</h1><p>This pre-launch page is operated for VeriPeers by Xplorevo Private Limited.</p><h2>Early-interest and partnership inquiries</h2><p>When you submit a form, the details you provide are securely saved for the VeriPeers team. You do not need to open or send an email yourself. Inquiry records are not publicly accessible.</p><h2>Information you choose to share</h2><p>An early-interest inquiry includes your name, role, email address, and selected interests. A partnership inquiry includes your organization, category, contact person, email address, and proposed collaboration.</p><h2>Purpose of your inquiry</h2><p>Your inquiry provides the VeriPeers team with the information needed to respond to you and discuss your interest or proposed collaboration. Inquiries are stored using Lovable Cloud. When email notifications are enabled, submission details will also be sent to hello@veripeers.com for the team to follow up.</p><h2>Privacy questions</h2><p>For questions about your information or to request that the team stop contacting you or remove your inquiry details, contact <a href="mailto:privacy@veripeers.com">privacy@veripeers.com</a>.</p><p className="privacy-disclaimer">This page describes the current pre-launch inquiry process. VeriPeers should provide its complete retention and privacy terms before introducing additional platform services.</p></main>; }
