import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowLeft } from 'lucide-react';
import logo from '@/assets/veripeers-logo.png.asset.json';
export const Route = createFileRoute('/privacy')({ head: () => ({ meta: [
  { title: 'Privacy Information — VeriPeers' }, { name: 'description', content: 'How to contact VeriPeers about your early-interest and partnership inquiry details.' },
  { property: 'og:title', content: 'VeriPeers — Privacy Information' }, { property: 'og:description', content: 'Privacy information for VeriPeers pre-launch inquiries and contact details.' },
  { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary' },
] }), component: Privacy });
function Privacy() { return <main className="container privacy-page"><Link to="/"><img src={logo.url} alt="VeriPeers" className="privacy-logo" /></Link><Link to="/" className="back-link"><ArrowLeft size={17} />Back to VeriPeers</Link><p className="eyebrow">YOUR INFORMATION MATTERS</p><h1>Privacy Information</h1><p>This pre-launch page is operated for VeriPeers by Xplorevo Private Limited.</p><h2>Early-interest and partnership inquiries</h2><p>The forms on this page prepare an email using the details you enter. Your inquiry is not submitted until you send that email through your chosen email service. This website does not save form entries to a lead database.</p><h2>Information you choose to share</h2><p>An early-interest inquiry includes your name, role, email address, and selected interests. A partnership inquiry includes your organization, category, contact person, email address, and proposed collaboration.</p><h2>Purpose of your inquiry</h2><p>Your email provides the VeriPeers team with the information needed to respond to your inquiry and discuss relevant launch updates or collaboration. Your email provider handles messages according to its own privacy terms.</p><h2>Privacy questions</h2><p>For questions about your information or to request that the team stop contacting you or remove your inquiry details, contact <a href="mailto:privacy@veripeers.com">privacy@veripeers.com</a>.</p><p className="privacy-disclaimer">This page describes the current pre-launch email inquiry process. A full Privacy Policy covering the launched platform will need to be provided by VeriPeers before new data-collection services are introduced.</p></main>; }
